= Instant Pot Rigatoni Firenze

== Ingredients

2 tbsp of extra virgin olive oil +
1 small yellow onion, diced +
1 tbsp of crushed garlic +
5-10 fresh basil leaves, plus one leaf per bowl for garnish +
28 oz can of Crushed tomatoes (use San Marzano if you can swing it – worth the difference) +
1.5 cups of garlic broth or chicken broth (I say 3/4 cup in the video, but I actually suggest 1.5
cups and go for 2.5 cups if using an 8qt instead of a 6qt) +
1/4 cup of a dry red wine (like a Pinot Noir but just use extra broth if you don’t want to use wine) +
1 tsp of kosher salt +
1 tsp of seasoned salt +
1 tsp of Italian seasoning +
1 tsp of oregano +
1 box (1 lb) of rigatoni +
1 cup of shredded Mozzarella cheese (use a creamy one if possible) +
1/4 cup of shredded or shaved Asiago cheese, plus more for garnish +

You can really use any cheese of your choice, but I suggest a melty cheese (like a creamy Mozzarella)
so it really mixes into the sauce.

Want the sauce a little creamier? Add in 1/3 cup of heavy cream after pressure cooking just before
stirring in the cheese.

Want it a little meaty? Sauté some Italian sausage (sweet or hot) with the onions until cooked, remove
with a slotted spoon before adding the pasta, set aside and then add back in when adding the cheese!

== Instructions

1. On the Instant Pot, hit “Sauté” and “Adjust” so it’s on the “More” or “High” setting. Add the olive
oil to the pot, heat it up and then add in the onion and sauté for 5 minutes
2. Add in the garlic and basil leaves in sauté for another minute with the onion
3. Pour in the broth and crushed tomatoes and give everything a stir
4. Next, add in the red wine, kosher salt, seasoned salt, oregano, Italian seasoning and stir
everything together once more
5. Then, add in the rigatoni and smooth it out so it’s submerged in the sauce but DO NOT STIR!
6. Secure the lid and cook for 8 minutes at high pressure for al dente (firmer, chewier) noodles  or
10 minutes for softer noodles. Quick release when done
7. When the lid comes off, stir the rigatoni up with the sauce so everything gets mixed together well
(NOTE: If the pasta seems not totally done or too al dente, it will be shortly as you will be stirring
it in the heated sauce for a few more moments when you add the cheese)
8. Add in the Mozzarella and Asiago and stir for about 3-5 minutes as the pasta continues to heat.
The cheese will be gooey and stretchy as first, but will then become hidden in the sauce on the
surface as it melds into the sauce. Once you dig into it, it will be ever so present.
9. Place some into individual bowls and top with additional shaved Asiago cheese and a basil leaf
for presentation
10. Enjoy!
