= Mexican Beans and Rice

This is a family favorite. It's quick and easy to prepare too.

|===
|Servings|6
|Prep. Time|10 minutes
|Cook Time|15 Minutes
|===

== Ingredients

[width="75%", cols="10,15,75"]
|===
|Qty |Measure |Ingredient
|1|tbs|extra virgin olive oil
|1|lb.|ground beef
|1||medium red onion
|1|tsp|chilli powder
|1/2|tsp|cumin
|1/2|tsp|salt
|2|cups|pre-cooked brown rice
|1|cup|long grain white rice
|2|cups|water
|2|cups|salsa (or 16 oz jar)
|1|15 oz can|black beans, drained and rinsed
|1|cup|corn
|2|tsp|brown sugar (can use less)
|3|tbs|fresh cilantro, chopped
|1 1/2|cup|shredded Mexican cheese
|===

== Preparation

. With your Instant Pot, click the saute function (or browning if on another brand). Allow the pot to come to temperature. When the screen reads `HOT` add in the olive oil, ground beef, onion, chilli powder, cumin, and salt.
. Saute for 3-5 minutes until the beef has become crumbled and brown.
. While the beef is cooking, measure 1 cup of white rice. Rinse the rice a few times to release starches. The rice is ready when the water draining off is clear. Rinsing prevents rice from getting mushy.
. Add rice, water, sals, black beans, and corn to the Instant Pot. Stir to combine.
. Close and lock the lid. Set to manual high pressure for 8 minutes.
. Quick release pressure and remove the lid. Stir in chopped cilantro and transfer to a serving platter.
. Top with cheese and serve.
