= Best Ever Instant Pot Roast

by https://pressureluckcooking.com/author/admin/[Jeffrey] | Apr 8, 2018

Source URL: https://pressureluckcooking.com/recipe/instant-pot-roast/

== Ingredients

*   3-5 lb chuck or rump (bottom) roast (**NOTE:** 3 lbs is perfect to me and will easily feed 4-5. Another excellent cut of meat to use are the boneless short ribs from Costco like the ones I use in my https://pressureluckcooking.com/recipe/instant-pot-short-ribs/[Short Rib Recipe] or a cut of meat that is labeled “Pot Roast.” Whichever you pick, make sure the cut of meat is nice and MARBLED – meaning there are plenty of strands of fat visible within the meat. This makes for the most tender roast)
*   1.5 tsp of kosher salt
*   1.5 tsp of seasoned salt
*   2 tsp of black pepper
*   1/2 tbsp of dried parsley
*   1 tsp of dried thyme
*   1 tsp of of dried rosemary
*   1 tsp of onion powder
*   1 tsp of garlic powder
*   2 tbsp of extra virgin olive oil
*   1 tbsp of salted butter
*   2 yellow onions, sliced longways into thick wedges
*   1 tbsp of sliced garlic
*   2 tbsp of Worcestershire sauce
*   6-8 oz of Portobello mushrooms, sliced
*   2 cups of beef broth
*   1 cup of a dry red wine (use one you would drink and not a red cooking wine – a Pinot Noir is great)
*   3 tbsp of cornstarch + 3 tbsp of water to form a slurry
*   1 oz packet of any beef gravy flavor (I used Au Jus but any will do)
*   **Veggies to be wrapped in foil:**
*   8-14 oz bag of baby carrots
*   1 lb of baby white potatoes (the best kind for this dish)

====
This is literally one of the best pot roasts I’ve ever had. Super rich in flavor and abundant in goodies. Follow this recipe to a T and I think you’ll agree.
Cooking the potatoes and carrots in separate foil pouches as opposed to being directly exposed in the pot while pressure cooking is a MAJOR tip in order to make sure they don’t turn into mush!

The sauce will be so plentiful and delicious, some may even think of this as a pot roast stew as you’ll want to lap it up with not only a spoon, but some crusty Italian or French bread!

While most recipes keep the cooking time the same if doubling recipes, roasts are an exception. Since roasts are thick cuts of meat, the time should be adjusted per pound. For this pot roast, cook at 60 minutes for 3 lbs, 70 minutes for 4 lbs and 80 minutes for 5 lbs. Allow a 15 min natural release regardless of how many pounds. But always use fresh (not frozen) meat for a pot roast if possible.
====

== Instructions

1.  Rub the roast all over with the kosher salt, seasoned salt, black pepper, dried parsley, dried thyme, dried rosemary, onion powder and garlic powder
2.  Add the olive oil to the http://amzn.to/2HkAa3Q[Instant Pot] (I used a 6qt) and hit “Sauté” and adjust so it’s on the “More” or “High” setting. Allow the oil to heat up for 3 minutes and then sear the seasoned roast in the oil for about 1-2 mins on each side. Remove the roast when done searing and set aside on a plate
3.  The bottom of the pot will likely have some spice remnants stuck on it from searing the meat. Add in the butter and as it melts, immediately scrape/deglaze the bottom of the pot with a wooden or plastic spoon to remove any remnants of the spices from the roast. Add the onions and they will release water as they cook making it easier to deglaze the bottom of the pot. Cook for 2 minutes an then add in the garlic and Worcestershire sauce and stir for another 2-3 minutes while deglazing. The bottom of the pot should be nice and smooth by now with most spices no longer stuck to it
4.  Place the trivet over the onions with the handles facing upwards and place the roast on top of the trivet, fat-side up (so it allows the juices to coarse through the meat as it cooks), along with the mushrooms. Pour the wine and beef broth over everything
5.  Lastly, securely wrap the potatoes and carrots in their own foil pouches and place in the pot on top of the roast (make room for it and it should fit fine as I did this in a 6qt). This will help the potatoes and carrots retain character and texture since they won’t be directly exposed to the pressure and will be a HUGE benefit to the final results
6.  Secure the lid and then hit “Pressure Cook” or “Manual” High Pressure for 60 mins* (see “Jeffrey Sez” section of the recipe for varying cooking times for larger roasts). When done, allow a 15 minute natural release (meaning you do nothing for 15 minutes) and then follow up with a quick release
7.  Once the lid comes off, first remove the foil-covered veggies and set aside and then carefully remove the roast using the trivet’s handles and flip it onto a cutting board. Allow to the roast and veggies to cool a few moments
8.  Go back to the pot, hit “Keep Warm/Cancel,” and then hit “Sauté” and adjust so it’s on the “More” or “High” setting and bring the sauce to a bubble. Unwrap the foiled potatoes and carrots and add/stir them into the sauce. Once the sauce bubbles, add the cornstarch slurry and stir immediately and then add in the gravy packet and stir. Allow to bubble for one minute and then turn the pot off and the sauce will become something so incredible, you may forget your name
9.  http://amzn.to/2trloX6[Using a good knife], slice up the pot roast against the grain in strips about 1/4 inch thick (or make thicker cuts if you wish). Then, cut each strip into good-sized chunks and immediately add them into the sauce and let sit in there for a few moments to soak it in. Make sure you toss in any remaining little strands of meat into the sauce too and give everything a final stir
10.  Serve on a plate or in bowls with some crusty French or Italian bread (for lapping up the sauce) and/or https://pressureluckcooking.com/recipe/instant-pot-white-rice/[rice]
11.  Enjoy!
++++
<center>© 2017 PressureLuckCooking.com</center>
++++