= Printable Instant Pot Chicken Piccata
by Jeffrey

== Ingredients

1.5 – 2 pounds of boneless/skinless chicken breasts, sliced about 1/4″ thick
1/2 cup of all-purpose flour (with a few pinches of garlic powder, parmesan, black pepper and
kosher salt mixed in), for dredging
1/4 cup of extra virgin olive oil
3 Tbsp of butter, divided
1 tbsp of crushed garlic
Juice of 2 fresh lemons
1 1/4 cups of chicken broth (1 1/4 tsp of Chicken Better Than Bouillon + 1 1/4 cups of water)
1/2 cup of half & half or heavy cream
1/3 cup of parmesan cheese
1 1/2 tbsp of cornstarch + 1 1/2 tbsp of water
Dried parsley flakes
Capers

This recipe will make some extra of that amazing sauce and you’ll be glad it does because it’s gonna
go GREAT over pasta! (I suggest a Cavatelli). Have a big group of folks coming over for company?  Double or triple it and just add another 2 minutes
of pressure cooking time per 1x amount you add! Like mushrooms and marsala?  Try my Chicken Marsala recipe as well!  Also to die for!

== Instructions

1. Coat chicken in flour mixed with with salt, pepper, parmesan and garlic powder and set aside
2. Hit “Sauté” on the Instant Pot and “Adjust” to the “More” setting and wait for it to read “Hot.” Add
the olive oil and 1 tbsp of butter until melted and let sit for 1 minute
3. Add the chicken in batches and lightly brown for about 1-2 minutes on each side. Remove, set
aside and repeat until all chicken is lightly browned. Chicken should be lightly browned like in the
video for reference
4. Add the garlic and stir constantly for 30 seconds until it begins to darken (but not burn!) and then
add the chicken broth and lemon juice. Scrape and deglaze the bottom of the pan and stir
5. Add the chicken back to the pot and layer so it covers the pot and rests on each other
6. Secure the lid, hit “Keep Warm/Cancel” and then hit “Manual” or “Pressure Cook” High Pressure
for 10 minutes. Quick release when done
7. Remove the chicken and place on a serving dish, but leave sauce in the pot, and hit “Keep
Warm/Cancel” and then hit “Sauté” again so it’s on “More”
8. Add the half & half, 2 tbsp of butter, parmesan and cornstarch slurry to the mixture right away
and stir/whisk in VERY well (we don’t want it bunching up), scraping the bottom of the pan and
then let the sauce cook. Do this for about 2-3 minutes as the sauce will begin to bubble and
thicken very quickly and then turn the pot off
9. Pour the sauce over the chicken in the serving dish and add some capers and sprinkle some
dried parsley (and some thin lemon slices if you’d like to garnish). Serve on its own or over
pasta, spaghetti squash, rice and/or vegetables!
10. Enjoy!
